# Change these first
owner: CountlessAI # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Countless App
    url: https://app.countless.ai
#  - name: Countless Dev
#    url: https://app-dev.countless.ai

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.countless.ai
  # baseUrl: /your-repo-name
  logoUrl: https://framerusercontent.com/images/hCq1M1kDOHLNNvoj03J1RoHmdy4.png
  name: Countless Status Page
  introTitle: "**Countless** is the all-in-one platform for financial decision-making."
  introMessage: This page provides relevant information about Countless services status, incidents and updates.
  navbar:
    - title: Status
      href: /
    - title: Get Countless
      href: https://countless.ai

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
